### ISSUE TITLE
Port the code for pings and unreads from DTM-16 v4 to v5

### ISSUE THREAD

**Issue by Diyamund** [XYZenix/XYZenixThemes#10]
Currently, DTM-16 v5 uses the new ping.
![image](https://user-images.githubusercontent.com/44238627/113780561-00d44f80-96f5-11eb-900f-ce60b2040867.png)
And the new unread size.
![image](https://user-images.githubusercontent.com/44238627/113780610-10539880-96f5-11eb-96ca-35de9a812a59.png)

**Comment by XYZenix** [comment]
you should move all those under one issue tbh

**Comment by XYZenix** [comment]
copied over like one thing from v4 in c1e4bd203c8fc7e948f4e964e7f74b6a0158de46 but i'll test it more tomorrow

**Comment by XYZenix** [comment]
should be done in bc4c5e325d1746c875e9f21191aa17597c522050
