### ISSUE TITLE
Direct Messages icon misplaced when native titlebar is removed [bug] [DTM-08]

### ISSUE THREAD

**Issue by CatmanFan** [XYZenix/XYZenixThemes#101]
When the native Discord titlebar is disabled via the CSS code `[class*=titleBar] { display: none !important; }`, the top-left Direct Messages icon gets displaced downward when I hover over it, and remains there until it is reloaded again (e.g. opening User Settings and then closing).

![Discord](https://github.com/XYZenix/XYZenixThemes/assets/30674270/dd1e3116-a188-481b-ac7f-c9c681d9e1f2)

Without the CSS code however it behaves normally.

![DiscordB](https://github.com/XYZenix/XYZenixThemes/assets/30674270/ce2a58d6-3f1e-44b8-82b2-3c327c9f35d0)

As of writing, it has not been fixed yet on DTM-08 v2

**Comment by XYZenix** [comment]
well it can't detect your custom css that hides the titlebar, it assumes titlebar is present on `platform-win` and missing on `platform-web` and i forgot what it does on `platform-osx`
you could probably replace `platform-win` in the theme's css with something random so it never gets selected (didn't test if this'd actually work) or use something that replaces the `platform-win` class on the html tag with `platform-web`

or just find the css that moves the button down and edit it to not do that (i'll probably post that later if no one does before me, i'm currently on a tiny break from everything, will probably be back tomorrow)

**Comment by XYZenix** [comment]
try this:
```css
.scroller__3d071 .tutorialContainer__890ea {
  top: 0 !important;
}
```

**Comment by CatmanFan** [comment]
Already done, will now close as being solved. Thank you
