### ISSUE TITLE
[DTM-08] Spoilers contrast is pretty awful

### ISSUE THREAD

**Issue by ByJumperX4** [XYZenix/XYZenixThemes#106]
Hi XYZenix,
I love this theme, but I have _one_ issue with it right now, it's the color of spoilers that makes them essentially invisible.
See picture attached
![image](https://github.com/XYZenix/XYZenixThemes/assets/48773926/57398522-02cf-4434-942f-605bbe25f6f7)

**Comment by XYZenix** [comment]
just to confirm, are you using DTM-08 V1 or V2 because i don't think the version in the bd repo got updated

**Comment by ByJumperX4** [comment]
I'm using the V2 on Vesktop

**Comment by XYZenix** [comment]
okay should be fixed now in https://github.com/XYZenix/XYZenixThemes/commit/b43e75707bb2d9fd402437fc6561b4c32161c69b

**Comment by ByJumperX4** [comment]
I think at the bottom of the background gradient it still pretty much looks the same but definitely an improvement
![image](https://github.com/XYZenix/XYZenixThemes/assets/48773926/4a0d09b4-c5bf-44cc-8d7d-0097b9ca40d3)
![image](https://github.com/XYZenix/XYZenixThemes/assets/48773926/ee5128b0-4776-4d3e-84af-402e5d877174)
