### ISSUE TITLE
don't forget about the weird ass emoji redesign! >_<

### ISSUE THREAD

**Issue by kwan-vini** [XYZenix/XYZenixThemes#108]
![image](https://github.com/XYZenix/XYZenixThemes/assets/118130060/95ce8980-7f87-4fac-b005-64a16b4dd1fa)
![image](https://github.com/XYZenix/XYZenixThemes/assets/118130060/a33d9da2-53d7-446b-abb6-1d58ff24870c)

thanks discord! i love having broken theme elements while using a theme!

**Comment by XYZenix** [comment]
which theme is this

**Comment by kwan-vini** [comment]
> which theme is this

oops i forgot to tag it, its dtm-16 v5

**Comment by XYZenix** [comment]
already fixed, did you refresh the theme in the last 12 hours

**Comment by kwan-vini** [comment]
> already fixed, did you refresh the theme in the last 12 hours

no, i'll check later

**Comment by ezra-351** [comment]
having this issue on dtm-18, installed like just now. dtm-16 works tho

**Comment by XYZenix** [comment]
dtm-18 is not my theme

**Comment by arceuss** [comment]
still happens on dtm-17
