### ISSUE TITLE
[bug] [DTM-08] "Call timer" not working with DTM-08 V2

### ISSUE THREAD

**Issue by c4ndeo** [XYZenix/XYZenixThemes#109]
The Vencord plugin "Call timer", which is supposed to display a call timer in the "Voice Connected" field in the call controls. 
This worked fine in pre-version 2, but it doesn't show up now. See attached screenshots for comparison.
![Screenshot 2023-12-19 142757](https://github.com/XYZenix/XYZenixThemes/assets/92527260/bb1b0fdd-02f5-4bc5-bdda-bbe1fe445bd0)
![Screenshot 2023-12-19 142936](https://github.com/XYZenix/XYZenixThemes/assets/92527260/d0542213-7ce8-4dc7-a8ce-7cc5d6f5f6a7)

**Comment by XYZenix** [comment]
i personally can't fix client mod plugin related issues anymore so would be greatly appreciated if someone would open a pull request for this
