### ISSUE TITLE
Change server dropdown icon to a hamburger icon (DTM-16)

### ISSUE THREAD

**Issue by Diyamund** [XYZenix/XYZenixThemes#11]
Currently, it uses the new one.
![image](https://user-images.githubusercontent.com/44238627/113780842-66284080-96f5-11eb-925b-abedfd6465c5.png)
This is what it used to look like
This could be applied to both v4 and v5.

**Comment by XYZenix** [comment]
i would do this but as of rn i can't think of any way to properly do the animation and until i figure something out, i'm not bringing it back
