### ISSUE TITLE
Not sure if this is an issue with the theme or the "read all" button plugin, but there is a big gap between the home button and the channels

### ISSUE THREAD

**Issue by xxHAKRxx** [XYZenix/XYZenixThemes#110]
![image](https://github.com/XYZenix/XYZenixThemes/assets/140458341/2b74bc25-2e2e-473a-b89c-4bd17182857d)

**Comment by XYZenix** [comment]
i completely forgot to look into this issue.
what client mod is this? if it's not vencord - **exactly** what plugin is it? what other plugins do you have enabled? is this still an issue? etc.

**Comment by xxHAKRxx** [comment]
I'm using Vencord and it's "Read all" plugin

**Comment by XYZenix** [comment]
i'm also confused about the...double...server list? idk what's going on in that screenshot

**Comment by xxHAKRxx** [comment]
It's another plugin I downloaded where servers in folders are put in a separate bar

**Comment by MysticAx0lotl** [comment]
![image](https://github.com/XYZenix/XYZenixThemes/assets/69944483/04a529bf-d3f8-401a-bf37-15f71f2127a2)
Same issue with ArmCord 3.2.6, using Vencord as a client mod

**Comment by XYZenix** [comment]
there are way too many client mods and custom clients and i personally don't want to install every single one of them to make sure my themes work with all of them and all their individual plugins so if any issue arises from those, people can open pull requests to fix the issues

**Comment by MysticAx0lotl** [comment]
This is definitely a Vencord issue, Armcord by itself is one-to-one compatible with themes meant for the official client

**Comment by XYZenix** [comment]
i think this was fixed? reopen this issue if not i'm too tired to check
