### ISSUE TITLE
Nitro themes dont work 

### ISSUE THREAD

**Issue by robler64** [XYZenix/XYZenixThemes#111]
as the title says, nitro themes dont change the colors of this theme

**Comment by XYZenix** [comment]
please specify which theme you're referring to. i'm assuming DTM-16, in which case, that's intentional; i tried to make nitro themes work before and it looked awful so i chose to discard that idea

**Comment by XYZenix** [comment]
actually should've clarified, i assume you meant *profile* themes

if you mean app color themes, those only work in DTM-16 and not DTM-08 because there's no good way i can think of to implement those into DTM-08

**Comment by XYZenix** [comment]
i have an idea for how to handle color themes in DTM-08, but i'll wait until discord stable is on a version of electron/chromium that supports `color-mix`

**Comment by XYZenix** [comment]
closing as invalid because the author of this issue did not even bother to specify which theme they're referring to, and discussing DTM-08's support of color themes here may not even be relevant to what this issue was supposed to be about
