### ISSUE TITLE
Muted Microphone Icon Replaced By Red Square [DTM-16]

### ISSUE THREAD

**Issue by tragedians** [XYZenix/XYZenixThemes#112]
Not quite sure if it is an issue per se, but we recently noticed that the muted microphone icon at the lower part of the interface where the user settings are located suddenly has come to be replaced by a red square - with the normal microphone icon remaining intact.

We have tried to disable the version we got from betterdiscord and download the css file directly from the source here on github, to see if there were any update changes that the site did not catch up to (and made the theme break), but nothing really changed. That is the only visual issue we have noticed so far, but were curious to know if it was a deliberate change or not.

EDIT: The theme currently in use is DTM-16

![01](https://github.com/XYZenix/XYZenixThemes/assets/132375228/4c2cbc5e-d411-4bae-978c-ee6bc69fd95b)

**Comment by XYZenix** [comment]
this should be fixed now
