### ISSUE TITLE
[DTM-16] Add the ability to disable all new feature like profile banner, color and more to recreate the closest 2016 Discord experience

### ISSUE THREAD

**Issue by B1ue-Dev** [XYZenix/XYZenixThemes#113]
Like the title said, I found out a mod call [oldcord](https://github.com/milbits/oldcord) that tries to replicate the 2020 Discord UI experience with all new features like banner color and so on removed. It will be neat if this is a thing inside DTM-16 as well.

**Comment by XYZenix** [comment]
can you provide a list of everything you want removed

**Comment by XYZenix** [comment]
- original friend icon was restored at some point, i guess it broke and i never noticed? i'll fix that later
- online count is not doable without a plugin and i don't really plan to support plugins on my own, but anyone can open a pull request if they want a plugin to work better with my themes
- i could make a theme addon (a theme you apply on top of the main theme) to hide profile banners
- that shouldn't be gray, it should be blurple, as it's based on this profile ui from sep 2016
![sep 2016 profile ui](https://github.com/XYZenix/XYZenixThemes/assets/51988432/2758518e-4b72-4a62-b982-7080ae4c7c38)
- profile ui needs to be redone in general (at the very least the full profile ui, the profile popout works for now but the full profile ui has a lot of issues i have to sort out at some point in the future)

**Comment by XYZenix** [comment]
i decided to revisit this issue, and:
- the friends icon for the home button is already there - i don't remember if it was broken at the time or not
- profile banners are staying both to not hinder server moderation and to not cause confusion, idk when i will get around to making a mini-theme to hide banners though, but when i do i'll close this issue with it
- color banners should be hidden from user popouts already, but i'll have to think about what to do with the full profile banner
