### ISSUE TITLE
[DTM-08] Reply, react, pin, etc. icons not showing up when hovering over messages

### ISSUE THREAD

**Issue by tifawockhart** [XYZenix/XYZenixThemes#115]
![image](https://github.com/XYZenix/XYZenixThemes/assets/161201581/a6503b92-33b1-4aea-92a1-00558e167648)
Pretty self explanatory, I've tried reinstalling the theme several times and I tried editing it myself to no avail as well.

**Comment by XYZenix** [comment]
is this v1 or v2
v1 broke because of the expiring attachment urls update and i'd rather just continue maintaining v2 only

**Comment by tifawockhart** [comment]
v2

**Comment by XYZenix** [comment]
just checked, nope, you're using v1 - the gradients in your screenshot match v1 and not v2, and v2 doesn't break icons in that action bar

**Comment by tifawockhart** [comment]
oh my fault i thought i enabled v2 :c
