### ISSUE TITLE
Theme is completely broken now

### ISSUE THREAD

**Issue by xxHAKRxx** [XYZenix/XYZenixThemes#116]
For some reason the glossy/skeuomorphic effects on the theme are now gone, all that's left are the fonts and some layout changes
![image](https://github.com/XYZenix/XYZenixThemes/assets/140458341/5865eeb0-6687-4722-8f0a-b1f707e46dea)

**Comment by ComfortableMilk4454** [comment]
11pixels stopped maintaining all his themes recently so thats probably why, i just tested on my end and i see the same thing you see

**Comment by XYZenix** [comment]
> 11pixels stopped maintaining all his themes recently so thats probably why, i just tested on my end and i see the same thing you see

i only lost motivation to continue working on them, i'm going to continue doing the bare minimum to ensure they function
this'll take ages to fix manually so i'm going to wait a day or two and if nobody comes up with a quick method to do this, i'll fix it myself
in the meantime idk don't restart discord or something

**Comment by forkiesassds** [comment]
Right now the update that broke the theme is not out on stable, well it was out for some time but was rolled back.

**Comment by ComfortableMilk4454** [comment]
its defo out on stable cuz im running stable discord and this is what i see
![image](https://github.com/XYZenix/XYZenixThemes/assets/43555540/5fd2f85e-1168-4161-af34-b463954683a4)
