### ISSUE TITLE
DTM-08-V2 bug 11pixels asked me to post here

### ISSUE THREAD

**Issue by ComfortableMilk4454** [XYZenix/XYZenixThemes#117]
![image](https://github.com/XYZenix/XYZenixThemes/assets/43555540/1906c2b6-9482-4f7e-9efb-abee9b54e774)
![image](https://github.com/XYZenix/XYZenixThemes/assets/43555540/e5026562-3a6d-4970-83e8-ac0ca690ae19)

**Comment by XYZenix** [comment]
should be (poorly) fixed in one of the recent commits
