### ISSUE TITLE
[DTM-08] Checkboxes aren't showing up on firefox

### ISSUE THREAD

**Issue by smugvee** [XYZenix/XYZenixThemes#118]
Just works™ on chromium based browsers
![](https://github.com/XYZenix/XYZenixThemes/assets/85663797/213416bf-869f-4d9d-8df9-ad483fa13d4f)
But on firefox its all like "nah have a blue dot instead" and the check boxes become un-clickable
![](https://github.com/XYZenix/XYZenixThemes/assets/85663797/47b440d2-e185-498e-8a89-29ad4e83e122)
Only tested using Vencord because i'm lazy

**Comment by XYZenix** [comment]
firefox skill issue, can't fix

**Comment by smugvee** [comment]
thank u .... ❤️
