### ISSUE TITLE
[DTM-08] Friends/Home Button is displaced when running Discord with native titlebars

### ISSUE THREAD

**Issue by Kenst1092** [XYZenix/XYZenixThemes#123]
See upper left location where the friends/home button is located

![image](https://github.com/XYZenix/XYZenixThemes/assets/20787137/993db383-89fb-4ab8-8fb5-392414915483)

- Discord Stable 275565
- Vencord 6e36381
- OpenAsar Nightly 4f264d8
- Using your auto-updated DTM-08 theme as a local file via Vencord
- Despite the window frame appearing like Aero Glass, I'm running Windows 10 22H2 build 19045.4046.

I most certainly do not believe the extras on top of my Discord client is the issue, I was previously using the latest version of BetterDiscord and the issue was present there as well.

It's more of a visual nuisance than anything, it still functions like normal.

**Comment by XYZenix** [comment]
try this in custom css:
```css
.platform-win .scroller__3d071 .tutorialContainer__890ea {
  top: 0 !important;
}
```

**Comment by XYZenix** [comment]
closing as won't fix because as far as i can tell, vencord doesn't add literally any selector to anything to detect whether the native titlebar option is enabled or not
