### ISSUE TITLE
DTM-17 icons broken again

### ISSUE THREAD

**Issue by VictorTheVictor** [XYZenix/XYZenixThemes#124]
Discord updated again, and the icons broke again. I tried DTM-18, which was never patched to the last icon bug, and the icons worked normally, so perhaps reverting those changes might fix it? Discord PWA, Chromium (Supermium) 122, Vencord web.

**Comment by XYZenix** [comment]
i stopped working on DTM-17 some time ago and i'm not going to maintain it anymore

**Comment by VictorTheVictor** [comment]
Yeah, but can you maybe provide an older version from before the icon patch?
