### ISSUE TITLE
[DTM-08] Poll's dont look right.

### ISSUE THREAD

**Issue by Wingzzzzy** [XYZenix/XYZenixThemes#128]
Just puting this hear to hope that who ever works on this can fix it 
![image](https://github.com/XYZenix/XYZenixThemes/assets/20495150/e8c6adfe-cf78-4b34-ad1c-92eeef6c851a)
![image](https://github.com/XYZenix/XYZenixThemes/assets/20495150/f51e01f3-cf16-4671-8fef-cd5595290c26)

Version DTM-08 V2 Build 100 Updated on Apr 9, 2024

**Comment by ArbestRi02** [comment]
well
newest dtm-08
![Screenshot 2024-05-11 at 9 16 35 PM](https://github.com/XYZenix/XYZenixThemes/assets/168323856/b87e933e-ff0f-479a-9add-e62a728f4f98)
