### ISSUE TITLE
[DTM-08] Keeps saying there is an update while there isn't

### ISSUE THREAD

**Issue by Lifell** [XYZenix/XYZenixThemes#13]
BetterDiscord keeps telling me that there is an update for this theme. Once updated it just repeats the process next time you launch Discord or reload Discord.

I tried deleting the theme completely and redownloading it. Didn't fix anything.

**Comment by XYZenix** [comment]
im aware of this but i dont think this has to do with the theme and more likely has something to do with themerepo or bd

for the record, there was a problem with submitting this theme for a while that had to do with the dash in the theme name, idk if that's related to this bug though

**Comment by XYZenix** [comment]
hmm i will go fix that rn

**Comment by XYZenix** [comment]
...that didn't really fix it for me so nevermind lol

**Comment by Lifell** [comment]
That's weird. It works for me. I even changed it back to the original "AUTO" and reloaded Discord. Got greeted with the "Update" notification again. So it's definitely working somehow.

**Comment by XYZenix** [comment]
ok so it works fine now, i guess there was something to do with cache earlier idk lol
