### ISSUE TITLE
[all] Replace "APP" text with "BOT"

### ISSUE THREAD

**Issue by FurblandChannel** [XYZenix/XYZenixThemes#130]
for some reason the bot badge now says "APP" (just discord being stupid as usual). you might wanna change that back.

**Comment by XYZenix** [comment]
![image](https://github.com/XYZenix/XYZenixThemes/assets/51988432/6e5d9989-1dd7-4cfd-9898-c7099062634a)
or use one of the snippets posted in every client mod's discord server's css snippets channel as i am not going to be responsible for anything breaking from trying to change a string of text

**Comment by XYZenix** [comment]
i also can't change every instance of "app" with "bot" especially in tooltips so good luck fixing that without js and i'm sure someone would complain if i fix this but not everything else (like the 'verified app' tooltip)
