### ISSUE TITLE
Server boost icon - DTM-16

### ISSUE THREAD

**Issue by atqr1** [XYZenix/XYZenixThemes#131]
Would be nice if the theme reverted the boost icon shown on servers to the old icon (without the home symbol) from <2022

Current:
![image](https://github.com/XYZenix/XYZenixThemes/assets/119353097/8f72ea76-7945-40fd-8873-f12c8fdb6fa7)

The only way to get the old icon currently is by having level 2/3 without it being a community server

**Comment by XYZenix** [comment]
this can't be fixed without js, and my themes use only css
