### ISSUE TITLE
[DTM-08] logo in the corner is shifted downwards

### ISSUE THREAD

**Issue by FlashlightET** [XYZenix/XYZenixThemes#132]
![image](https://github.com/XYZenix/XYZenixThemes/assets/29938499/2ca3c52c-9eec-465d-807e-81e729139603)

logo in the corner you click on to get to the friends list is shifted downwards (using live css for v2)

i use 125% zoom but it happens at 100% too

**Comment by XYZenix** [comment]
are you using vencord's native titlebar feature

**Comment by FlashlightET** [comment]
fair point! let me disable that

**Comment by FlashlightET** [comment]
yeah that fixed it lol

**Comment by XYZenix** [comment]
forgot to mention it here but this should be properly fixed now and native titlebar shouldn't have this issue anymore
