### ISSUE TITLE
fix the profiles

### ISSUE THREAD

**Issue by Venus5687** [XYZenix/XYZenixThemes#135]
discord changed some of the profile popups recently and this is what they look like now (except for the bots)
![immagine](https://github.com/XYZenix/XYZenixThemes/assets/96628563/12d6ec7d-e7af-45de-bb70-1d1d2b06708f)
![immagine](https://github.com/XYZenix/XYZenixThemes/assets/96628563/bbfd6cfb-9a1d-491a-b3c2-c6a8b24a3b5f)

**Comment by XYZenix** [comment]
enable experiments and find the "simplified profiles" experiment and set it to control i am not dealing with this right now

**Comment by Venus5687** [comment]
ok

**Comment by ArbestRi02** [comment]
> enable experiments and find the "simplified profiles" experiment and set it to control i am not dealing with this right now ![image](https://private-user-images.githubusercontent.com/51988432/331815992-2ab70452-b10a-4681-b0b2-40c2dd4f7a08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzkzNTMsIm5iZiI6MTcyMTY3OTA1MywicGF0aCI6Ii81MTk4ODQzMi8zMzE4MTU5OTItMmFiNzA0NTItYjEwYS00NjgxLWIwYjItNDBjMmRkNGY3YTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDIwMTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMDBhYmE1MGUzMzBkMjc1NTdkNDEzYjhkM2FmMjYxZDIwNTNhNGE2YTllZjc4MmMzNGZhMDUzYzdkMzM2N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ULKWZ2Ady0gQy_h8-oMrckQ59vbMMz6FNtCNgbWGWA)

As of now the Simplified Profiles experiment toggle is gone.

**Comment by XYZenix** [comment]
the experiment was removed from the client nearly a month ago
