### ISSUE TITLE
[Suggestion] Merge DTM-16 and DTM-16 v5

### ISSUE THREAD

**Issue by Diyamund** [XYZenix/XYZenixThemes#14]
DTM-16 v5 is more accurate in a lot of places, but lacks in features such as status icons.

It would be great if you could just merge the 2 themes, and have them be one.

**Comment by XYZenix** [comment]
dtm-16 v5 uses scss so i'd have to copy stuff from dtm-16 (v4) to v5 instead. i'll probably start actually working on dtm-16 v5 again soon and replace v4 with it

**Comment by XYZenix** [comment]
will be replacing current dtm-16 with v5 soon k bye
