### ISSUE TITLE
Visual bug with horizontal server list theme

### ISSUE THREAD

**Issue by ThreeStepsNeeded** [XYZenix/XYZenixThemes#142]
![image](https://github.com/XYZenix/XYZenixThemes/assets/171815974/75630d6d-b106-4878-bdf3-a13164a53a0a)
When you have your cursor on the Discord button, this weird vertical thing will appear. Does not happen with the horizontal server list theme disabled. Using Discord on web.

Thank you

**Comment by XYZenix** [comment]
please provide link to the theme

**Comment by ThreeStepsNeeded** [comment]
Thanks!
