### ISSUE TITLE
[DTM-16] the shop exists

### ISSUE THREAD

**Issue by Sinphy** [XYZenix/XYZenixThemes#143]
it was a gif of a parrot before i want him back

**Comment by XYZenix** [comment]
the shop existing is not a bug and the parrot gif hasn't been functional since the expiring attachment url system was rolled out. the rule was that if anyone complained about the silly zone existing, i remove it. someone did complain, and it was broken anyway, so it had to go.

**Comment by redshirtsdiefirst** [comment]
i want the parrot back

**Comment by davart154** [comment]
![image](https://github.com/XYZenix/XYZenixThemes/assets/111528101/e0753778-2a99-4764-b04c-7902fe46d166)
