### ISSUE TITLE
dtm-08: the top left discord logo and notification icons are missing there unique textures

### ISSUE THREAD

**Issue by robotimdevloper** [XYZenix/XYZenixThemes#144]
idk if i put that wording right.

the discord logo in the top left doesnt have all the stuff and is off center to the left because of that.

all the notifcation icons also are having the similar issue, as they are no longer squares but the normal circles they are without said theme

sorry if this whole thing sucked in terms of wording idk how to write one of these good so im sorry

**Comment by davart154** [comment]
He is aware of this problem. His power went out so he won't be able to fix this stuff until it's back on.
