### ISSUE TITLE
They did it again (all Discord themes broken)

### ISSUE THREAD

**Issue by forkiesassds** [XYZenix/XYZenixThemes#146]
~~Seems to be canary and PTB only for now~~ Pushed to all branches

**Comment by XYZenix** [comment]
bold of you to assume i haven't already started fixing my themes :trollface:

**Comment by HunterBoy344** [comment]
holy shit that was fast

**Comment by forkiesassds** [comment]
Old :pleading_face: emoji is GONE on DTM-16...
