### ISSUE TITLE
[DTM-08] Left edge of embed looks misaligned

### ISSUE THREAD

**Issue by TexNat** [XYZenix/XYZenixThemes#15]
![image](https://user-images.githubusercontent.com/64905176/117584349-0e08a380-b0d2-11eb-9ee2-3e09002fae93.png)
the light inside edge isn't quite up against the border as you can see here.

Also, not really an issue but i think it would really add to the look if you made some glossy button icons that would match the era. Fantastic theme btw, i miss when this kind of stuff was the standard

**Comment by XYZenix** [comment]
not sure i understand what the problem is, the small bar on the left is the embed bar that can have a custom color, it's like that on purpose

**Comment by TexNat** [comment]
oh i see, i was just looking at it wrong. since it's basically the same color as the background i thought there was a gap in it. my bad
