### ISSUE TITLE
Blurred profile menu

### ISSUE THREAD

**Issue by coughrelief** [XYZenix/XYZenixThemes#151]
The profile menu is blurred after new discord update. The one where you change status, etc. I'm using vencord.
![image](https://github.com/XYZenix/XYZenixThemes/assets/136914587/55877d04-a6c6-4c7f-a236-e4dfc52c140d)

**Comment by parappatherappr** [comment]
ive been having the same exact problem 😭 such a shame, i love the theme

**Comment by XYZenix** [comment]
enable experiments and find the "Simplified Profile Experiment" and set it to Control

**Comment by parappatherappr** [comment]
tried that and it works, but it does revert the profile ui back to the old version unfortunately. i wish it stayed the same, but it'll have to do for now. thank you!

**Comment by XYZenix** [comment]
fixed it anyway lol
