### ISSUE TITLE
[DTM-16] "Add App" Window

### ISSUE THREAD

**Issue by Venus5687** [XYZenix/XYZenixThemes#154]
Why is the "Add App" window like this.
![immagine](https://github.com/XYZenix/XYZenixThemes/assets/96628563/39f8e410-7e16-4ec5-9f55-bbc21fe0378b)

**Comment by Venus5687** [comment]
it isn't alligned with the window

**Comment by XYZenix** [comment]
this was fixed at some point so closing this issue
