### ISSUE TITLE
DTM-08 V2: More things broken

### ISSUE THREAD

**Issue by ArbestRi02** [XYZenix/XYZenixThemes#158]
![image](https://github.com/user-attachments/assets/7611d0a0-4ced-427d-a335-f79f45a12cc1)
This box thing isn't styled anymore after the latest DTM-08 V2 update.

**Comment by XYZenix** [comment]
i fixed earlier it i just forgot to push the update lol check again in a few minutes

**Comment by ArbestRi02** [comment]
Also the top buttons on the simplified profiles are not styled.
![image](https://github.com/user-attachments/assets/f95c47bd-5027-4efd-9f9a-134bea5a2617)
