### ISSUE TITLE
Brace for impact...

### ISSUE THREAD

**Issue by Diyamund** [XYZenix/XYZenixThemes#16]
Discord is planning an AWFUL redesign.
You can enable it by going to [Discord Canary's online version](https://canary.discord.com/), enabling the experiments tab and enabling `2021-04_product_redesign`.

You should definitely make a theme to revert this.

**Comment by XYZenix** [comment]
i think you meant rebrand?
i'm gonna make DTM-20 (based on early 2020) a thing now because i can't really properly revert the on/off switches to the old green color
