### ISSUE TITLE
Message settings don't look glossy

### ISSUE THREAD

**Issue by xxHAKRxx** [XYZenix/XYZenixThemes#162]
![image](https://github.com/user-attachments/assets/9bd15098-6d91-414b-b6d7-1a53069530c8)

**Comment by XYZenix** [comment]
what build number? are you in the `2024-07_hover_bar_reaction_suggestions` experiment? etc. etc. more details please

**Comment by ComfortableMilk4454** [comment]
@xxHAKRxx thats a you issue doesn't happen for me. how are you getting the theme, vencord, betterdiscord, stylus extension, etc. what dtm08 version?
![CleanShot 2024-08-10 at 13 43 06@2x](https://github.com/user-attachments/assets/c25c390f-ffab-4bf1-b19f-26bb734073d0)

**Comment by ComfortableMilk4454** [comment]
the latest version is dtm-08 v2 build 136 as of writing. make sure you are not using v1 as that was deprecated in favor of v2.

**Comment by xxHAKRxx** [comment]
> what build number? are you in the `2024-07_hover_bar_reaction_suggestions` experiment? etc. etc. more details please

I'm using V2
![image](https://github.com/user-attachments/assets/163ca0a4-5bbf-4634-b585-13c7cb025e85)

Here's a full screenshot if you want more proof
![image](https://github.com/user-attachments/assets/80bb2bbc-e1de-4c38-aa55-665ce2d9bdf8)

**Comment by XYZenix** [comment]
sorry for late response but...you are (or were) using an outdated version of the theme lol
