### ISSUE TITLE
[DMT-08] Custom statuses seem to be breaking profiles

### ISSUE THREAD

**Issue by smugvee** [XYZenix/XYZenixThemes#166]
![image](https://github.com/user-attachments/assets/fb0f1326-d355-4fc9-84d8-5026a2345dbe)
yep

**Comment by smugvee** [comment]
spelled itwrong
   ... . . . . DTM

**Comment by XYZenix** [comment]
what theme version
what app version
this doesn't happen on my end

**Comment by smugvee** [comment]
updated to latest, that fixed it my bad
