### ISSUE TITLE
[DTM-08] "New" button doesn't dissappear

### ISSUE THREAD

**Issue by I-am-Sachi** [XYZenix/XYZenixThemes#171]
![image](https://github.com/user-attachments/assets/cf6b446c-9207-4338-9bc6-017cf2df6266)
When I use DTM-08 /w SkeuoCord, the "New" button doesn't disappear and covering my DM button

**Comment by XYZenix** [comment]
why are you using 2 full themes at the same time

**Comment by I-am-Sachi** [comment]
I wanted a background but DTM-08 seemed to not have any background changing support so I used SkeuoCord to add background

**Comment by I-am-Sachi** [comment]
I only have 2 issues with that combo, working so well tbh.
the second issue I'm having with is this space filling my message box.
![image](https://github.com/user-attachments/assets/6c1d7d64-4a21-4781-8c69-ef68fea6874f)
other than that, I can use this combo freely.
