### ISSUE TITLE
[DTM-08] seems to be broken after most recent update

### ISSUE THREAD

**Issue by Pomi108** [XYZenix/XYZenixThemes#172]
Discord just updated and now no DTM-08 theming is being applied. Other themes seem to work fine. I'm on PTB if that matters.

**Comment by XYZenix** [comment]
10 reasons not to use PTB:

**Comment by XYZenix** [comment]
....jokes aside, they're doing something with ptb so it's probably best to just use stable or canary for now (especially since ptb usually gets the same updates as canary)

**Comment by Pomi108** [comment]
Oh, I thought this must've been a Discord-wide issue. I take it that the theme still works on latest canary and stable?

**Comment by XYZenix** [comment]
it was a discord-wide issue, they seem to have reverted it from what i can tell but if everything breaks again i'll try and figure out what to do about it
