### ISSUE TITLE
Embeds padding

### ISSUE THREAD

**Issue by aubymori** [XYZenix/XYZenixThemes#18]
![image](https://user-images.githubusercontent.com/44238627/118349296-837ed480-b515-11eb-9a0e-7de8edfdee71.png)

This was in a video from late 2017. I don't know if it was like this in 2016, but I hope this helps.

**Comment by peepee** [comment]
one of my own screenshots from 2016 using discord's default css for better reference
![discord 2016 embed](https://user-images.githubusercontent.com/49787675/153604205-82a185dc-e98c-405a-85e4-48edb3be4845.png)

**Comment by peepee** [comment]
> i think i made a mini-theme/addon for dtm-16 that makes embeds look like this b ut idk if i ever updated it
yeah it doesn't work anymore lol
