### ISSUE TITLE
Would like screenshots of the various themes

### ISSUE THREAD

**Issue by K4sum1** [XYZenix/XYZenixThemes#19]
I think it would help to have screenshots of your themes to help new users determine what they like the best.

**Comment by XYZenix** [comment]
there are a few partially outdated screenshots on https://xyzenix.github.io/XYZenixThemes/DTM-16/

i'll add new screenshots somewhere (most likely the dtm-16 and dtm-08 repos) probably when i stop procrastinating

as for why only dtm-16 and dtm-08, well the other themes aren't getting any updates from me anytime soon but if i ever get back to working on them (most likely only dtm-12) i'll add screenshots for them as well (ofc in their own repos for pc/bd)

**Comment by K4sum1** [comment]
Lazy

**Comment by XYZenix** [comment]
https://github.com/XYZenix/DTM-16/ and https://github.com/XYZenix/DTM-08/

**Comment by K4sum1** [comment]
> https://github.com/XYZenix/DTM-16/ and https://github.com/XYZenix/DTM-08/

Oh, sorry, I only looked at this, expecting them to be here.

**Comment by XYZenix** [comment]
this repo is (at least as of now) for issues and the css stuff and whatnot, the DTM-16 and DTM-08 repos are for quickly getting the themes

idk if anyone even uses anything else that is in this repo that doesn't have its own repo by now, but if that is the case, let me know

**Comment by K4sum1** [comment]
Didn't notice that, but yeah, that is likely better than having everything in one repo.

Waiting for a Skeuomorphic + Glossy Steam update (It doesn't even work these days lmao)
