### ISSUE TITLE
DTM 16 theme

### ISSUE THREAD

**Issue by gabe7384** [XYZenix/XYZenixThemes#2]
On the theme when you add it on powercord with css (not sure if you use powercord or betterdiscord) and I was not able to scroll down onto my css again so i was not able to see below the Windows Settings tab. If you can maybe add a scrollbar or scrollable tabs so it dosnt happen. Please fix :) (very nice theme btw)

**Comment by XYZenix** [comment]
if i understood this correctly, the problem is with the user settings scrollbar, right?
i don't have any such problem, so i don't think i can fix it. what version of DTM-16 are you using?

**Comment by gabe7384** [comment]
Not sure what version but ill send link and yes it was on the settings scrollbar https://github.com/XYZenix/Discord-Themes/tree/master/DTM-16

**Comment by XYZenix** [comment]
the link you're using is of the old abandoned repo, i moved all my themes (including the auto-updating versions) to XYZenixThemes 
use this https://github.com/XYZenix/XYZenixThemes/blob/master/autoupdate/DTM-16.theme.css

**Comment by gabe7384** [comment]
oh lmao ok thanks maybe delete the other one if its abandoned so it dosnt happen to anyone else
