### ISSUE TITLE
DTM-08 hides the public servers button

### ISSUE THREAD

**Issue by PORTB** [XYZenix/XYZenixThemes#24]
The public servers button at the top server list is hidden when using DTM-08:
Without dtm
![image](https://user-images.githubusercontent.com/34615701/125902143-4a4c8773-f2d9-4ade-89fd-8639af4f2acf.png)
With dtm
![image](https://user-images.githubusercontent.com/34615701/125902187-63d64b49-824f-438c-8c2f-3962c1e9adc9.png)

**Comment by XYZenix** [comment]
should be fixed now
