### ISSUE TITLE
[DTM-16] logo and titlebar

### ISSUE THREAD

**Issue by peepee** [XYZenix/XYZenixThemes#32]
any way to get rid of this eyesore logo?
![image](https://user-images.githubusercontent.com/49787675/153607781-83a2b77a-1c39-49ae-aeca-76a3fe094f7f.png)

actually, is there any way to forgoe the 2017 titlebar entirely and revert back to the window controls being inside the canvas, like this?
![image](https://user-images.githubusercontent.com/49787675/153608086-d9e64206-381d-4d92-88af-16df71cbf076.png)

**Comment by XYZenix** [comment]
use a plugin for that. i originally used to find that annoying to use so i didn't want to force it into the theme, but i know there's a bd plugin out there that can emulate that (it's called OldTitleBar)

**Comment by peepee** [comment]
> use a plugin for that. i originally used to find that annoying to use so i didn't want to force it into the theme, but i know there's a bd plugin out there that can emulate that (it's called OldTitleBar)

sad, my client doesn't support external js plugins
dream dead

**Comment by XYZenix** [comment]
well, before i knew of the oldtitlebar plugin there was a theme to do it but i don't remember who made it or anything and messing with the titlebar is something i haven't done but i'll try something eventually
