### ISSUE TITLE
[DTM-16] call ui

### ISSUE THREAD

**Issue by nanopone** [XYZenix/XYZenixThemes#34]
call ui lacks the classic background, the call ui goes inside the top banner, and the buttons are arranged incorrectly
current:
![image](https://user-images.githubusercontent.com/49787675/153722232-30df7159-0eed-4c96-8b3d-03fe15cd64e2.png)
old:
![image](https://user-images.githubusercontent.com/49787675/153722290-2dd24a43-6d8b-4f0a-9851-8f2816614ab2.png)

**Comment by peepee** [comment]
wow you are fast, i did not expect to see it looking basically perfect just 24 hours later
