### ISSUE TITLE
[DTM-16] friends icon

### ISSUE THREAD

**Issue by nanopone** [XYZenix/XYZenixThemes#35]
friends icon is still the new one
current:
![image](https://user-images.githubusercontent.com/49787675/153722362-ebe295ba-0c9f-4d41-85dc-b955698a5a9c.png)
old:
![image](https://user-images.githubusercontent.com/49787675/153722358-05e57d0f-f5a5-4915-bd2f-60802bf68036.png)

**Comment by XYZenix** [comment]
reason i didn't revert this is because i couldn't find a good substitute icon for the other tabs (which as of now are the library tab and nitro tab) and i don't want to make it inconsistent
