### ISSUE TITLE
[DTM-16] inbox

### ISSUE THREAD

**Issue by peepee** [XYZenix/XYZenixThemes#36]
inbox could maybe be replaced with the old @ symbol?
current:
![image](https://user-images.githubusercontent.com/49787675/153722479-7f17040a-d5f7-46da-b504-8f061d0fe7b2.png)
old:
![image](https://user-images.githubusercontent.com/49787675/153722494-39ce0f02-7e73-427c-b9bb-2267ee7e3fab.png)

**Comment by XYZenix** [comment]
i might do this as a mini-theme because the inbox *contains* the recent mentions tab, but also isn't *just* the recent mentions tab, which is why i haven't changed this icon

closing for now, i'll look for the icon and do a mini-theme / theme addon later
