### ISSUE TITLE
[DTM-16] broken looking full screen call ui buttons

### ISSUE THREAD

**Issue by nanopone** [XYZenix/XYZenixThemes#38]
![image](https://user-images.githubusercontent.com/49787675/153777747-99a7bb6d-b4a0-497b-a2e7-d3a36e5814a9.png)
![image](https://user-images.githubusercontent.com/49787675/153777749-069b5aa9-e825-4259-a72c-b0121ebc4cbb.png)

**Comment by XYZenix** [comment]
will fix it when i can replicate it

also in what case does the second one occur?

**Comment by peepee** [comment]
i'm unable to replicate it alone in a private server now, but when i took the screenshot i was in a channel with a few people and one person was streaming but it wasnt focused

**Comment by XYZenix** [comment]
from what i can tell, this has been fixed by now, so i'm closing this
