### ISSUE TITLE
[DTM-16] Line near Home icon

### ISSUE THREAD

**Issue by Pixel556** [XYZenix/XYZenixThemes#39]
The line is near the home button. It disappears when i hover over it.
![image](https://user-images.githubusercontent.com/95143545/155061794-c8d2f015-8e9e-4515-a084-e5d041131f49.png)
Can this be fixed? I'm running v5

**Comment by XYZenix** [comment]
are you sure this is a DTM-16 issue? i can't reproduce this bug whatsoever

**Comment by Pixel556** [comment]
Yeah. This is a DTM-16 issue. It's there when I apply the theme.

**Comment by XYZenix** [comment]
i can't replicate this. what discord client are you using, on what OS?

**Comment by Pixel556** [comment]
I'm using the normal client, And i'm using Windows 11.

**Comment by Pixel556** [comment]
Oh wait, the line disappeared completely. Seems like it's not a bug.
