### ISSUE TITLE
[DTM-16] Channel line 2px

### ISSUE THREAD

**Issue by Pixel556** [XYZenix/XYZenixThemes#40]
I started on Discord in 2015. The blurple line was 4px. 
But now, In 2022, When i downloaded and enabled the theme, The blurple line size wasn't what i saw in 2015. It was 2px. 
![image](https://user-images.githubusercontent.com/95143545/155287456-7f1a8e6c-ac5b-4c6b-8495-f172e563a15b.png)
Can you adjust the size of it to 4px? I know that this issue was closed, and it still wasn't 4px.

**Comment by XYZenix** [comment]
it was 2px when i joined discord in 2016, and the theme is trying to resemble december 2016 discord. i'll add a variable to control this later.

**Comment by Pixel556** [comment]
Okay, that's fine.
