### ISSUE TITLE
[DTM-16] Connections tab colors are weird

### ISSUE THREAD

**Issue by dstnct** [XYZenix/XYZenixThemes#44]
![4KGXBRlY](https://user-images.githubusercontent.com/76597629/176575023-11fc6af1-7e06-4566-937d-c632a3495143.png)

**Comment by XYZenix** [comment]
i... did not account for the fact that someone might be in this many sub enabled servers... also that was supposed to work at one point but since i am not in any sub enabled servers i can't theme that so it'll have to wait until whenever i can i guess

**Comment by XYZenix** [comment]
ok so i might be able to fix this in about a week

**Comment by dstnct** [comment]
> i... did not account for the fact that someone might be in this many sub enabled servers... also that was supposed to work at one point but since i am not in any sub enabled servers i can't theme that so it'll have to wait until whenever i can i guess

I get some gift subs here and there, trust me i didn't knew aswell haha
