### ISSUE TITLE
[DTM-08] Retry button has no texture

### ISSUE THREAD

**Issue by jeedrb** [XYZenix/XYZenixThemes#45]
title

![image](https://user-images.githubusercontent.com/98370763/177298436-50662049-b584-4b90-9454-34040cd6da27.png)

**Comment by jeedrb** [comment]
Odd, I tried downloading from here and the BD website but they're both missing it.

Here's my system if it matters:
![image](https://user-images.githubusercontent.com/98370763/177459427-94f0a32d-983b-47a0-9181-c4fa12ef6a9c.png)

**Comment by XYZenix** [comment]
are you using web discord (if so, what browser?) or desktop discord? stable, ptb, or canary?
i still can't replicate this issue

**Comment by jeedrb** [comment]
Seems to have been fixed in the patch that also fixed #46.
![image](https://user-images.githubusercontent.com/98370763/178596207-5fd87d8a-c4e6-4258-9d9e-0f392b7c198c.png)
