### ISSUE TITLE
[DTM-08] Replying to message offset

### ISSUE THREAD

**Issue by jeedrb** [XYZenix/XYZenixThemes#49]
Replying to a message slightly lowers all messages, and cancelling/sending the reply puts it back to normal.
Normal
![image](https://user-images.githubusercontent.com/98370763/178597008-f8602edd-97eb-42d4-8590-5356e8b0cfe0.png)
Replying (you can now see the top of the 'E' and 'C' in "Edit Channel")
![image](https://user-images.githubusercontent.com/98370763/178597168-6942c46b-6580-440e-9770-5c39ebca98d6.png)

**Comment by XYZenix** [comment]
i tried to fix this in b28613a14c9629ce44a22c67916f881387eb06e1 but i'll leave this issue open just in case i broke something else

**Comment by jeedrb** [comment]
It's now fixed on my end
