### ISSUE TITLE
[DTM-08] Slash Command Hint Text

### ISSUE THREAD

**Issue by jeedrb** [XYZenix/XYZenixThemes#52]
After typing a slash command and hitting space/tab (in this case, the bot is Dyno), the hint text is overlapped by the bot icon and typed command.
![image](https://user-images.githubusercontent.com/98370763/179121733-156da3cf-e886-474a-88e0-be5c680c02cb.png)

**Comment by XYZenix** [comment]
did you update dtm-08? i already fixed this earlier

**Comment by jeedrb** [comment]
You update these fast wow
