### ISSUE TITLE
[DTM-08] Search wiggle

### ISSUE THREAD

**Issue by jeedrb** [XYZenix/XYZenixThemes#53]
Search result tabs move slightly when hovering over/between them, with no effect on New, slight movement on Old, and more movement on Relevant.

![image](https://user-images.githubusercontent.com/98370763/179272991-eaf3d975-1c63-4bfd-bac7-c13204614b2d.png)

https://user-images.githubusercontent.com/98370763/179272174-fc2e0ebf-23fb-4cf4-974b-57737ed661be.mp4

**Comment by XYZenix** [comment]
it's because of font weight changing on hover, i thought it looked cool and it did in settings, but i don't know why it's affecting this, will look into it later
