### ISSUE TITLE
[DTM-16] Messages are rendered wrongly

### ISSUE THREAD

**Issue by edo9300** [XYZenix/XYZenixThemes#54]
I think those images will explain better than i could 
![image](https://user-images.githubusercontent.com/18705342/179361807-c1f88bc9-7bbd-43cf-be88-ba03cc77dedb.png)
![image](https://user-images.githubusercontent.com/18705342/179361821-5b3c9ba0-f6f0-4592-adb9-b6e8da52f786.png)
(the blue line here is the "missing" text being selected
![image](https://user-images.githubusercontent.com/18705342/179361837-5704ca00-de30-4be6-b1ed-f6e607e45d59.png)
I noticed that it glitches out when you jump to a message, via link, from a search result or from a reply

**Comment by aubymori** [comment]
Can confirm this happens to me too.
![image](https://user-images.githubusercontent.com/44238627/179362705-002edf45-2cd1-47dc-b87a-6917fd4fc1e5.png)

**Comment by XYZenix** [comment]
ok at this point i'm just gonna rework messages completely, this has caused me so many problems and has become a huge mess, though idk if i should temporarily disable the message css or keep it as it is until i fix it
