### ISSUE TITLE
[DTM-16] Deafen, mute, and settings are all gone 

### ISSUE THREAD

**Issue by Nieveria** [XYZenix/XYZenixThemes#56]
![image](https://user-images.githubusercontent.com/68787710/180092227-5d815d0a-2c41-4018-99b0-ae9b0e3505ba.png)
When I enable the theme, all three buttons disappear so I can't access the settings unless I reload discord (which provides a 1-2 second gap between plugins loading for me to click on the settings icon)

**Comment by XYZenix** [comment]
you can access user settings using ctrl + ,
i see the problem (custom status too long)
will fix rn
