### ISSUE TITLE
[DTM-16] Open, Minimise, and Close buttons are black on Mac.

### ISSUE THREAD

**Issue by zx331645** [XYZenix/XYZenixThemes#57]
self explanatory. BetterDiscord 1.6.3, macOS 12.3.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/63444823/189458589-65fb0ca6-c1a1-4e06-8c9f-c30d852b142f.png">

**Comment by XYZenix** [comment]
i love not having access to a mac to fix this 💀
time to get a macOS vm

**Comment by XYZenix** [comment]
let me know if that fixes it

**Comment by zx331645** [comment]
yep fixed
