### ISSUE TITLE
[DTM-08] Reply Chain Tip Text

### ISSUE THREAD

**Issue by jeedrb** [XYZenix/XYZenixThemes#59]
![image](https://user-images.githubusercontent.com/98370763/190460618-c8c0c900-398f-43c2-948c-2e29345a298b.png)
Text indicating to use a thread over a 3rd chain reply sits in the message box instead of on top of it.
![image](https://user-images.githubusercontent.com/98370763/190461103-79296eb5-80f8-4dc7-a34a-21ab4011141f.png)
(I've never _not_ had the out of date text, regardless of importing the file with Custom CSS or by using the normally installed version)

**Comment by XYZenix** [comment]
if you have the outdated text then you're not using the css from the dtm-08 repo itself
