### ISSUE TITLE
Old channel look for DTM-16

### ISSUE THREAD

**Issue by Diyamund** [XYZenix/XYZenixThemes#6]
Hi! The channels in 2015/16 on Discord looked different.
![image](https://user-images.githubusercontent.com/44238627/113777974-6c1c2280-96f1-11eb-8cde-87cadf4f5dee.png)
Here's what they looked like.
Please make them look like this! (Note; Do not restore the arrow on voice channels, as its functionality is gone.)

**Comment by XYZenix** [comment]
i'm not sure i understand which part of this you're asking for

**Comment by XYZenix** [comment]
assuming you're asking about the channel height and the blurple bar being 4px instead of 2px, i can do that
if it's not that, then idk what you're asking for

**Comment by Diyamund** [comment]
yeah that, as well as the font-size being smaller, btw this is for the original, not v5
and the color of unselected text

**Comment by XYZenix** [comment]
should be done with ddecfa08059d0bcba86ed25d73e9b1fa6399d307 (except the selected channel bar, i want to keep it 2px since in my opinion the 4px one belongs more in DTM-15 than DTM-16)
