### ISSUE TITLE
Blank space

### ISSUE THREAD

**Issue by daraenvy** [XYZenix/XYZenixThemes#63]
for some reason there is a blank space under a line of text on some channels

**Comment by XYZenix** [comment]
1. which theme
2. any screenshots?

**Comment by daraenvy** [comment]
![image](https://user-images.githubusercontent.com/114296930/197629149-3e646d5f-2327-4535-bf3e-8636092ce658.png)

**Comment by daraenvy** [comment]
> 1. which theme
> 2. any screenshots?

dtm 16

**Comment by XYZenix** [comment]
is that an empty channel (i.e. no messages before that one)? if so, that's on purpose

**Comment by daraenvy** [comment]
> is that an empty channel (i.e. no messages before that one)? if so, that's on purpose

![image](https://user-images.githubusercontent.com/114296930/197629312-d1324295-e4ee-4492-852e-ccc88e9de2b8.png)

**Comment by daraenvy** [comment]
> is that an empty channel (i.e. no messages before that one)? if so, that's on purpose

yes

**Comment by XYZenix** [comment]
yeah, that's intentional

**Comment by daraenvy** [comment]
> yeah, that's intentional

is there a way for me to remove it

**Comment by XYZenix** [comment]
try this ```css
.scrollerContent-2SW0kQ {
  justify-content: flex-end;
}
```

**Comment by daraenvy** [comment]
> 



> try this
> 
> ```css
> .scrollerContent-2SW0kQ {
>   justify-content: flex-end;
> }
> ```

thank you it worked
