### ISSUE TITLE
[DTM-16/17] Favorites and Frequents emojis icons/buttons

### ISSUE THREAD

**Issue by MiraakThuri** [XYZenix/XYZenixThemes#64]
Hey, great thx for your work on those themes
I have an issue with the Favorites and Frequents emojis icons/buttons (it's the same on both themes)
they show up as a square with a question mark inside, instead of display the expected icons/buttons

![Sans titre](https://user-images.githubusercontent.com/69920875/200475079-c9b8b6db-9fed-4b75-a3ca-5efd4e522ab8.png)

PS: what would you recommand me to use to compile .scss (i would like to try some of the aviable settings, but online websites always fail)

**Comment by XYZenix** [comment]
the icons are broken on purpose as i was too lazy to make custom ones so i decided to leave them as it is until i eventually get around to making custom icons (which ended up never happening)

as for compiling scss, i use [dart sass](https://sass-lang.com/dart-sass) (installed with `npm install -g sass`, if i remember correctly)

**Comment by MiraakThuri** [comment]
I see, well maybe one day then
thx for the suggestion, ill try it out when i have some time

BTW, the speech green circle (that shows up when you talk) still use the "modern" darker green color instead of the old brighter one

**Comment by XYZenix** [comment]
hmmm i'll see if i can fix that later
