### ISSUE TITLE
[DTM-16] Font issue

### ISSUE THREAD

**Issue by elaymm4** [XYZenix/XYZenixThemes#72]
Got similar issue someone had here about a month ago (#69 #). Theme still keeps new font. Tried reinstalling both Discord itself and BetterDiscord.
DTM-16 Build 320
Stable 165943

**Comment by davart154** [comment]
The stuff for the font was recently removed as some of the links themselves are gone or have restricted access applied. It's in his best interest to not rehost the font in his theme as doing so would put his GitHub at risk. So that means gg sans will still be used for a bit. Hope this helps.
