### ISSUE TITLE
DTM-08 add server screen incorrect colors

### ISSUE THREAD

**Issue by K4sum1** [XYZenix/XYZenixThemes#77]
imo the white at the bottom kinda fire but the text hard to read

![ScreenShot_202303240520541](https://user-images.githubusercontent.com/77039240/227499152-adf9169f-d249-45bd-9087-cbdf81502c6f.png)
![ScreenShot_202303240520591](https://user-images.githubusercontent.com/77039240/227499149-955e0d94-e1ce-4ddd-a5f7-359b542f75f5.png)

**Comment by K4sum1** [comment]
fast

**Comment by K4sum1** [comment]
Does it take a bit to get pushed? I restarted my client and I still have it. Or is this a weird Vencord problem?

**Comment by XYZenix** [comment]
are you using the raw link or the github pages (github.io) link? if the former, try adding a question mark to the end of the url or something to refresh cache

**Comment by K4sum1** [comment]
https://xyzenix.github.io/XYZenixThemes/DTM-08/dtm-08.css

Adding a ? did fix it though.
