### ISSUE TITLE
[DTM-16] Unread messages in channel alert is too high

### ISSUE THREAD

**Issue by Rezhx** [XYZenix/XYZenixThemes#80]
![image](https://github.com/XYZenix/XYZenixThemes/assets/86567222/b89af321-3c40-4549-885c-e33072588a19)

The little glow-up thingy that shows whenever a channel has an unread message is not aligned with the channel name. Not sure if this is intended, but I'm pretty confident it was not like this until recently.

**Comment by XYZenix** [comment]
i really should stop waiting for discord to fix their own bugs if they're gonna take this long to fix them

**Comment by XYZenix** [comment]
i fixed this and forgot to close the issue lol
