### ISSUE TITLE
[DTM-08] Profile card is blurred and Discord logo in the upperleft corner overlays on it

### ISSUE THREAD

**Issue by fagirton** [XYZenix/XYZenixThemes#85]
![image](https://github.com/XYZenix/XYZenixThemes/assets/48362005/2068c7a2-22e7-489a-91d1-433b8c8205d1)
I thought it's an option in stream mode, but that doesn't happen when I disable the theme

**Comment by XYZenix** [comment]
the logo overlapping the popout occurs without the theme as well so /shrug
