### ISSUE TITLE
[DTM-08] Custom plugin buttons aren't visible on hover menu

### ISSUE THREAD

**Issue by justtryingthingsout** [XYZenix/XYZenixThemes#88]
As the title says, the buttons on the hover menu aren't visible except for the ones that come on Discord already. I'm not quite sure if this is where this issue could be posted since it could also be with the plugin developers' icons, but I think it would be great if there was at least a default color instead of being invisible.
<img width="325" alt="Hover menu with icons missing, hovering on the Quick Mention button" src="https://github.com/XYZenix/XYZenixThemes/assets/31097061/e3a6f4a5-01b8-4047-9cfd-6f0082158d56">
<img width="322" alt="Hover menu with icons missing" src="https://github.com/XYZenix/XYZenixThemes/assets/31097061/8d86924c-7416-4103-a6bb-e1c7644e7d5a">
This happens to the HideAttachments, ViewRaw, Translate, and QuickMention plugins on Vencord. I'm not sure if it happens to any other plugins that use this, nor am I sure of any other DTM themes causing this, as I haven't tested them yet.

**Comment by XYZenix** [comment]
you should consider using DTM-08 V2 since i'm going to phase out the current one soon
https://github.com/XYZenix/XYZenixThemes/tree/master/DTM-08-V2
idk if i will ever fix this on the current version of DTM-08 since i'm trying to focus on finishing v2

**Comment by justtryingthingsout** [comment]
DTM-08 V2 does indeed seem to fix the issue, I'll stay on that then, thanks! Should I close the issue, even through the bug technically hasn't been fixed on the old version?

**Comment by XYZenix** [comment]
i'll keep this issue open until i finally get around to replacing v1 with v2 (not actually removing v1, just replacing the primary links (i.e. the imports in the DTM-08 repo) to point to v2)
