### ISSUE TITLE
[DTM-16] Add back old image attachment appearance

### ISSUE THREAD

**Issue by forkiesassds** [XYZenix/XYZenixThemes#90]
Since October 4th 2023 Discord has removed the old Media Mosaic experiment toggle (well at least on canary), meaning it is no longer possible to disable the more mobile oriented appearance of attachments, this also includes the sizing of attachments. If it's possible to make it so how it was, either through this theme or possibly even a plugin it would be greatly appreciated.

**Comment by XYZenix** [comment]
i don't think i can recreate the previous behavior in a decent way, videos in a mosaic will always open in a popout and images may end up being blurry

also i don't usually rely on experiments for my themes so if i could do it in a good way, i would've done it by now. i think the best option would be to find a plugin that reverts the new functionality as i don't see css alone being able to do it very well

**Comment by forkiesassds** [comment]
> i think the best option would be to find a plugin that reverts the new functionality as i don't see css alone being able to do it very well

Problem is that there is no plugin to revert such behaviour, I had to use the experiment's control flag to revert it.
