### ISSUE TITLE
New update bricked DTM-16 on Vencord (possibly BD too)

### ISSUE THREAD

**Issue by FerroSan** [XYZenix/XYZenixThemes#91]
On my end, the DTM-16 theme (BD plugin with Vencord) doesn't seem to work ever since a new Discord update that dropped earlier today. I tried restarting, reinstalling Vencord and custom themes, reinstalling Discord, restarting my machine, etc. None of these have worked. I suspect that BD is also affected, though I have not tested that. I will also point out that this theme is not unique in its inability to function; it seems most BD/Vencord themes presently fail to work. 
Attached here are images of Vencord's validator and a cloud settings notice:
![image](https://github.com/XYZenix/XYZenixThemes/assets/33472406/567dc9e7-c951-469e-a370-5fe18017333b)
![image](https://github.com/XYZenix/XYZenixThemes/assets/33472406/ad331eba-1ce3-4299-aaf4-5ca731331bcb)

**Comment by XYZenix** [comment]
idk about the old discord font one, but... `https://github.com/XYZenix/DTM-16` itself isn't a link to a css file so ofc it wouldn't work, i'm pretty sure on vencord you have to link to the css file of the theme, not the repo the theme is in

**Comment by FerroSan** [comment]
My mistake. I retried it here. No hits.
![image](https://github.com/XYZenix/XYZenixThemes/assets/33472406/63d52fb7-19e8-4f5c-be7b-627feb6b1857)

**Comment by FerroSan** [comment]
Still seems to be borked. None of the links to DTM-16's css seem to work. Any idea on what the problem might be, if it's on my end or if the theme doesn't work at all? (really sucks too cus i love this theme)

![image](https://github.com/XYZenix/XYZenixThemes/assets/33472406/97b38def-5aec-4049-a368-231e8e303377)

![image](https://github.com/XYZenix/XYZenixThemes/assets/33472406/1a9e2081-f116-4fd0-b4c7-9b02416bed17)

**Comment by XYZenix** [comment]
use `https://xyzenix.github.io/XYZenixThemes/DTM-16-V5/DTM-16.css` or the **raw link** (`https://raw.githubusercontent.com/XYZenix/XYZenixThemes/master/DTM-16-V5/DTM-16.css`)

**Comment by FerroSan** [comment]
The first thing worked. Thanks a lot!
