### ISSUE TITLE
All Xyzenix's themes have issues with performance

### ISSUE THREAD

**Issue by haxerman123** [XYZenix/XYZenixThemes#92]
I have no idea why but performance is absolutely tanked with dtm 16, 8 and 17 for no reason...  Where is it tanked? when i type in chats, when i hover over servers in my server list, when i change my settings in the settings menu, mute deafen etc. all of the themes have this effect and i have no idea why.

**Comment by XYZenix** [comment]
i know dtm-16 can be laggy at times but... dtm-08? i don't think dtm-08 has ever had performance issues as far as i'm aware. how powerful is your device and are you using web or desktop discord? if web, what browser?

**Comment by haxerman123** [comment]
discord electron 22, chromium (supermium) on windows 7, pc specs athlon x2 5000+ 8gb ddr2 ram rx 570. yes i know that the gpu is overkill but without any of those themes discord runs flawlessly

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by haxerman123** [comment]
https://cdn.discordapp.com/attachments/871351640798662660/1155382307646087188/unknown_2023.09.24-07.55.mp4

**Comment by haxerman123** [comment]
no gpu usage which seems to be a hardware acceleration issue on chrome

**Comment by haxerman123** [comment]
but also sometimes it doesn't crumple discord to pieces in lag and most of the times it does and i have no clues as to why

**Comment by XYZenix** [comment]
issue "moved" to #94
