### ISSUE TITLE
dtm 8 and 17 are killing the performance on discord

### ISSUE THREAD

**Issue by haxerman123** [XYZenix/XYZenixThemes#94]
currently dtm 8 and 17 are killing performance while dtm 16 runs with no issues

https://github.com/XYZenix/XYZenixThemes/assets/89024496/976abe6f-b512-4ee2-a322-26bb3ee38d98

**Comment by XYZenix** [comment]
can you confirm if this occurs without client mod plugins


also this is a duplicate issue so i'm closing the previous one

**Comment by haxerman123** [comment]
i guess its pluginrepo causing that issue....... because before i opened it everything was working fine until i decided to use dtm 8 and then dtm 16 also started lagging wtf is happening with dsicords electron

**Comment by XYZenix** [comment]
try disabling all plugins, then restart discord, then enable the theme

**Comment by haxerman123** [comment]
will do

**Comment by haxerman123** [comment]
s

https://github.com/XYZenix/XYZenixThemes/assets/89024496/3a1ed9df-d290-4942-aac7-9b9464af9590

ame issue

**Comment by haxerman123** [comment]
here is dtm 17

https://github.com/XYZenix/XYZenixThemes/assets/89024496/17a874d0-a01d-4550-ad9b-ab587367ddb0

**Comment by XYZenix** [comment]
everything considered, even if i were to rewrite the theme, i don't think that'd help and i don't know any way to make it run better.

> while dtm 16 runs with no issues
this makes literally no sense because dtm-17 is just a modified dtm-16 and i can't imagine any case where dtm-08 would run worse than dtm-16 so i have no idea what's going on with your setup

**Comment by haxerman123** [comment]
> everything considered, even if i were to rewrite the theme, i don't think that'd help and i don't know any way to make it run better.
> 
> > while dtm 16 runs with no issues
> 
> this makes literally no sense because dtm-17 is just a modified dtm-16 and i can't imagine any case where dtm-08 would run worse than dtm-16 so i have no idea what's going on with your setup

its most likely discord being discord as usual because electron 22 is ass when it comes to polaris chips

**Comment by XYZenix** [comment]
if you're certain it's an electron issue, i guess the only thing i can suggest is using web discord then

**Comment by haxerman123** [comment]
https://github.com/XYZenix/XYZenixThemes/assets/89024496/dc640044-f6e9-4327-ac59-dc447c2431c5

well as you can see its discords electron sucking shit because on browser its running fine (runs even better on firefox)

**Comment by XYZenix** [comment]
i personally wouldn't suggest using firefox for this because firefox lacks support for styling various elements like checkboxes (`:before` and `:after` pseudoelements to be exact), scrollbars, etc. which most of my themes rely on a lot, but if you don't mind those 2 things being broken, go ahead, i can't really recall anything else being broken in my themes on firefox right now but don't be surprised if it is

**Comment by haxerman123** [comment]
> i personally wouldn't suggest using firefox for this because firefox lacks support for styling various elements like checkboxes (`:before` and `:after` pseudoelements to be exact), scrollbars, etc. which most of my themes rely on a lot, but if you don't mind those 2 things being broken, go ahead, i can't really recall anything else being broken in my themes on firefox right now but don't be surprised if it is

the fix for scrollbars is just change your useragent to chrome 
the site hummus.sys42.net for example has broken scrollbars when you unzoom but if you change the useragent to chrome on firefox it will have no issues then

**Comment by sirenuf** [comment]
Can confirm on this, the performance is really poor when I use DTM-08 Vencord. Really sad but still a great theme. DTM-08 v2 runs like butter, however

**Comment by haxerman123** [comment]
none of the themes are currently functioning due to discords heavy rewrite of their internals... closing this

**Comment by DumbGameMaker** [comment]
DTM-08 functions fine for me, with performance issues
