### ISSUE TITLE
Latest Discord update changed class names of every element

### ISSUE THREAD

**Issue by forkiesassds** [XYZenix/XYZenixThemes#95]
All Discord themes are now broken. The last time every class name changed was in early 2022.

**Comment by XYZenix** [comment]
i know lol i'm slowly working on fixing everything

**Comment by myriapoleis** [comment]
came here to report the same thing. also, love the dtm-08 theme, thanks for making it

**Comment by XYZenix** [comment]
locking this for now, [discuss this in #Themes in the discord server](https://discord.gg/BtKQ2E3P) because i don't like treating github issues/discussions as a chat

**Comment by XYZenix** [comment]
fixed for the most part; if anything's still broken, feel free to open issues for whatever's broken
