### ISSUE TITLE
[DTM-16] Profile modal overflow is completely inaccessible

### ISSUE THREAD

**Issue by aubymori** [XYZenix/XYZenixThemes#98]
If somehow a profile is too tall to fit on your screen, it'll shrink to fit, but it won't be scrollable, so any contents that were cut off won't be accessible.

![image](https://github.com/XYZenix/XYZenixThemes/assets/44238627/243a856a-1797-4787-9490-c29c14d4d58f)

**Comment by XYZenix** [comment]
i hate discord's profiel ui i hate it so much i want it GONE

**Comment by XYZenix** [comment]
this should be fixed now
