### ISSUE TITLE
Profile icons and On/Off switches stick out too much on 2008 theme

### ISSUE THREAD

**Issue by xxHAKRxx** [XYZenix/XYZenixThemes#99]
Both the profile icons and the on/off switches in the settings don't change when you turn on the 2008 theme, which makes them stick out and ruins the immersion for me
![image](https://github.com/XYZenix/XYZenixThemes/assets/140458341/0fbf9ba2-bbd1-4dd7-b9df-78410b3fec18)
![image](https://github.com/XYZenix/XYZenixThemes/assets/140458341/35d2bad3-d138-4c41-bd7a-228bc2c4b679)

Skeucord managed to fix this by making the profile icons square and adding a border, along with making the switches look like actual switches instead of just a graphic
![image](https://github.com/XYZenix/XYZenixThemes/assets/140458341/07fd7b81-08e8-4578-97cf-c7877c348867)
![image](https://github.com/XYZenix/XYZenixThemes/assets/140458341/66c398b6-e27c-4a8e-90aa-bc929af99ed1)

**Comment by XYZenix** [comment]
use DTM-08 V2. i'm not making avatars square yet, but the switches are themed in DTM-08 V2 at least. i'll redo them later probably but well as i said, just use DTM-08 V2.
easiest option is to replace the import with `https://xyzenix.github.io/XYZenixThemes/DTM-08-V2/dtm-08-v2.css`

(i got tired of maintaining the mess of css that is DTM-08 V1 so i'm abandoning it)
